// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DialPipe(arg1, arg2) {
  return window['go']['main']['App']['DialPipe'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function StartPipeServe() {
  return window['go']['main']['App']['StartPipeServe']();
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}
