// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function DialPipe(arg1:string,arg2:string):Promise<session.Session>;

export function Greet(arg1:string):Promise<string>;

export function ListSessions():Promise<Array<session.Session>>;

export function StartPipeServe():Promise<session.Session>;

export function StopSession(arg1:string):Promise<void>;
