// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {store} from '../models';
import {adapter} from '../models';

export function CreateKey(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function DeleteKey(arg1:string):Promise<void>;

export function DialPipe(arg1:string,arg2:string):Promise<session.Session>;

export function Greet(arg1:string):Promise<string>;

export function ListKeys():Promise<Array<store.KeyInfo>>;

export function ListSessions():Promise<Array<session.Session>>;

export function ParseAddr(arg1:string):Promise<string>;

export function ResolveAddr(arg1:string):Promise<string>;

export function StartBrowse(arg1:string):Promise<session.Session>;

export function StartForward(arg1:string,arg2:Array<adapter.PortMapping>):Promise<session.Session>;

export function StartPing(arg1:string,arg2:boolean):Promise<session.Session>;

export function StartPipeServe():Promise<session.Session>;

export function StartPortServe(arg1:Array<adapter.PortMapping>):Promise<session.Session>;

export function StartRecv(arg1:string,arg2:boolean):Promise<session.Session>;

export function StartCopy(arg1:string,arg2:Array<string>,arg3:string):Promise<session.Session>;

export function StartFilesServe(arg1:string,arg2:string):Promise<session.Session>;

export function ListRemote(arg1:string,arg2:string):Promise<Array<adapter.FileEntry>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFiles(arg1:string):Promise<Array<string>>;

export function StartSSHServe(arg1:boolean,arg2:string,arg3:boolean):Promise<session.Session>;

export function StartSSHClient(arg1:string,arg2:string,arg3:string,arg4:string):Promise<session.Session>;

export function StartSOCKS(arg1:string,arg2:string):Promise<session.Session>;

export function StartExitNode():Promise<session.Session>;

export function StartExec(arg1:string):Promise<session.Session>;

export function GetNetworkSettings():Promise<store.Settings>;

export function SetNetworkSettings(arg1:string,arg2:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;
