// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMiaoReceive(arg1) {
  return window['go']['main']['App']['CancelMiaoReceive'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectChatPeer(arg1, arg2) {
  return window['go']['main']['App']['ConnectChatPeer'](arg1, arg2);
}

export function CreateKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateKey'](arg1, arg2, arg3);
}

export function DecodeChatVoice(arg1, arg2) {
  return window['go']['main']['App']['DecodeChatVoice'](arg1, arg2);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function DialPipe(arg1, arg2) {
  return window['go']['main']['App']['DialPipe'](arg1, arg2);
}

export function DiscardChatMessage(arg1, arg2) {
  return window['go']['main']['App']['DiscardChatMessage'](arg1, arg2);
}

export function DiscardMiaoReceive(arg1) {
  return window['go']['main']['App']['DiscardMiaoReceive'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetClientInfo() {
  return window['go']['main']['App']['GetClientInfo']();
}

export function GetNetworkSettings() {
  return window['go']['main']['App']['GetNetworkSettings']();
}

export function GetSSHDesk() {
  return window['go']['main']['App']['GetSSHDesk']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function EndMiaoShare(arg1) {
  return window['go']['main']['App']['EndMiaoShare'](arg1);
}

export function JoinMiaoShare(arg1, arg2) {
  return window['go']['main']['App']['JoinMiaoShare'](arg1, arg2);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListMiaoReceives() {
  return window['go']['main']['App']['ListMiaoReceives']();
}

export function ListRemote(arg1, arg2) {
  return window['go']['main']['App']['ListRemote'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function MiaoRestoreNotes() {
  return window['go']['main']['App']['MiaoRestoreNotes']();
}

export function MiaoShareStatus() {
  return window['go']['main']['App']['MiaoShareStatus']();
}

export function ParseAddr(arg1) {
  return window['go']['main']['App']['ParseAddr'](arg1);
}

export function RecordUpdateCheck() {
  return window['go']['main']['App']['RecordUpdateCheck']();
}

export function ResendChatFile(arg1, arg2) {
  return window['go']['main']['App']['ResendChatFile'](arg1, arg2);
}

export function ResolveAddr(arg1) {
  return window['go']['main']['App']['ResolveAddr'](arg1);
}

export function RevealDownloadedUpdate() {
  return window['go']['main']['App']['RevealDownloadedUpdate']();
}

export function RestartChatRoom(arg1, arg2) {
  return window['go']['main']['App']['RestartChatRoom'](arg1, arg2);
}

export function SaveChatFile(arg1, arg2) {
  return window['go']['main']['App']['SaveChatFile'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function SendChatFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChatFile'](arg1, arg2, arg3, arg4);
}

export function SendChatSignal(arg1, arg2) {
  return window['go']['main']['App']['SendChatSignal'](arg1, arg2);
}

export function SendChatText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChatText'](arg1, arg2, arg3, arg4);
}

export function SendChatVoice(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendChatVoice'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetMiaoReceiveDest(arg1, arg2) {
  return window['go']['main']['App']['SetMiaoReceiveDest'](arg1, arg2);
}

export function SetNetworkSettings(arg1, arg2) {
  return window['go']['main']['App']['SetNetworkSettings'](arg1, arg2);
}

export function SetUILocale(arg1) {
  return window['go']['main']['App']['SetUILocale'](arg1);
}

export function StartBrowse(arg1) {
  return window['go']['main']['App']['StartBrowse'](arg1);
}

export function StartChatRoom(arg1) {
  return window['go']['main']['App']['StartChatRoom'](arg1);
}

export function StartCopy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCopy'](arg1, arg2, arg3);
}

export function StartExec(arg1) {
  return window['go']['main']['App']['StartExec'](arg1);
}

export function StartExitNode() {
  return window['go']['main']['App']['StartExitNode']();
}

export function StartFilesServe(arg1, arg2) {
  return window['go']['main']['App']['StartFilesServe'](arg1, arg2);
}

export function StartMiaoReceive(arg1, arg2) {
  return window['go']['main']['App']['StartMiaoReceive'](arg1, arg2);
}

export function StartMiaoShare(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartMiaoShare'](arg1, arg2, arg3, arg4);
}

export function StartForward(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartForward'](arg1, arg2, arg3);
}

export function StartPing(arg1, arg2) {
  return window['go']['main']['App']['StartPing'](arg1, arg2);
}

export function StartPipeServe() {
  return window['go']['main']['App']['StartPipeServe']();
}

export function StartPortServe(arg1) {
  return window['go']['main']['App']['StartPortServe'](arg1);
}

export function StartRecv(arg1, arg2) {
  return window['go']['main']['App']['StartRecv'](arg1, arg2);
}

export function StartSOCKS(arg1, arg2) {
  return window['go']['main']['App']['StartSOCKS'](arg1, arg2);
}

export function OpenSSHShell(arg1, arg2) {
  return window['go']['main']['App']['OpenSSHShell'](arg1, arg2);
}

export function RemoveSSHPeer(arg1) {
  return window['go']['main']['App']['RemoveSSHPeer'](arg1);
}

export function SaveSSHPeer(arg1, arg2) {
  return window['go']['main']['App']['SaveSSHPeer'](arg1, arg2);
}

export function SetSSHAllowAny(arg1, arg2) {
  return window['go']['main']['App']['SetSSHAllowAny'](arg1, arg2);
}

export function SetSSHEnabled(arg1) {
  return window['go']['main']['App']['SetSSHEnabled'](arg1);
}

export function StartSSHClient(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSSHClient'](arg1, arg2, arg3, arg4);
}

export function StartSSHServe(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSSHServe'](arg1, arg2, arg3);
}

export function WriteSSHShell(arg1, arg2) {
  return window['go']['main']['App']['WriteSSHShell'](arg1, arg2);
}

export function StopChatRoom(arg1) {
  return window['go']['main']['App']['StopChatRoom'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function TailcatVersion() {
  return window['go']['main']['App']['TailcatVersion']();
}
