// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {main} from '../models';
import {store} from '../models';
import {adapter} from '../models';

export function CancelMiaoReceive(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function ConnectChatPeer(arg1:string,arg2:string):Promise<void>;

export function CreateKey(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function DecodeChatVoice(arg1:string,arg2:string):Promise<string>;

export function DeleteKey(arg1:string):Promise<void>;

export function DialPipe(arg1:string,arg2:string):Promise<session.Session>;

export function DiscardChatMessage(arg1:string,arg2:string):Promise<void>;

export function DiscardMiaoReceive(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<main.UpdateStatus>;

export function GetClientInfo():Promise<main.ClientInfo>;

export function GetNetworkSettings():Promise<store.Settings>;

export function GetSSHDesk():Promise<Record<string, unknown>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function Greet(arg1:string):Promise<string>;

export function EndMiaoShare(arg1:string):Promise<void>;

export function JoinMiaoShare(arg1:string,arg2:string):Promise<Record<string, unknown>>;

export function ListKeys():Promise<Array<store.KeyInfo>>;

export function ListMiaoReceives():Promise<Array<Record<string, unknown>>>;

export function ListRemote(arg1:string,arg2:string):Promise<Array<adapter.FileEntry>>;

export function ListSessions():Promise<Array<session.Session>>;

export function MiaoRestoreNotes():Promise<Array<string>>;

export function MiaoShareStatus():Promise<Array<Record<string, unknown>>>;

export function ParseAddr(arg1:string):Promise<string>;

export function RecordUpdateCheck():Promise<main.ClientInfo>;

export function ResendChatFile(arg1:string,arg2:string):Promise<void>;

export function ResolveAddr(arg1:string):Promise<string>;

export function RevealDownloadedUpdate():Promise<void>;

export function RestartChatRoom(arg1:string,arg2:string):Promise<session.Session>;

export function SaveChatFile(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFiles(arg1:string):Promise<Array<string>>;

export function SendChatFile(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<string>;

export function SendChatSignal(arg1:string,arg2:string):Promise<void>;

export function SendChatText(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<void>;

export function SendChatVoice(arg1:string,arg2:string,arg3:number,arg4:string,arg5:boolean,arg6:number):Promise<void>;

export function SetLaunchAtLogin(arg1:boolean):Promise<main.SystemInfo>;

export function SetMiaoReceiveDest(arg1:string,arg2:string):Promise<void>;

export function SetNetworkSettings(arg1:string,arg2:string):Promise<void>;

export function SetUILocale(arg1:string):Promise<void>;

export function StartBrowse(arg1:string):Promise<session.Session>;

export function StartChatRoom(arg1:string):Promise<session.Session>;

export function StartCopy(arg1:string,arg2:Array<string>,arg3:string):Promise<session.Session>;

export function StartExec(arg1:string):Promise<session.Session>;

export function StartExitNode():Promise<session.Session>;

export function StartFilesServe(arg1:string,arg2:string):Promise<session.Session>;

export function StartMiaoReceive(arg1:string,arg2:string):Promise<Record<string, unknown>>;

export function StartMiaoShare(arg1:Array<{name:string,path:string,dataBase64:string}>,arg2:number,arg3:boolean,arg4:number):Promise<Record<string, unknown>>;

export function StartForward(arg1:string,arg2:Array<adapter.PortMapping>,arg3:boolean):Promise<session.Session>;

export function StartPing(arg1:string,arg2:boolean):Promise<session.Session>;

export function StartPipeServe():Promise<session.Session>;

export function StartPortServe(arg1:Array<adapter.PortMapping>):Promise<session.Session>;

export function StartRecv(arg1:string,arg2:boolean):Promise<session.Session>;

export function StartSOCKS(arg1:string,arg2:string):Promise<session.Session>;

export function OpenSSHShell(arg1:string,arg2:boolean):Promise<session.Session>;

export function RemoveSSHPeer(arg1:string):Promise<Record<string, unknown>>;

export function SaveSSHPeer(arg1:string,arg2:string):Promise<Record<string, unknown>>;

export function SetSSHAllowAny(arg1:boolean,arg2:boolean):Promise<Record<string, unknown>>;

export function SetSSHEnabled(arg1:boolean):Promise<Record<string, unknown>>;

export function StartSSHClient(arg1:string,arg2:string,arg3:string,arg4:string):Promise<session.Session>;

export function StartSSHServe(arg1:boolean,arg2:string,arg3:boolean):Promise<session.Session>;

export function WriteSSHShell(arg1:string,arg2:string):Promise<void>;

export function StopChatRoom(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function TailcatVersion():Promise<string>;
