// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateKey'](arg1, arg2, arg3);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function DialPipe(arg1, arg2) {
  return window['go']['main']['App']['DialPipe'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ParseAddr(arg1) {
  return window['go']['main']['App']['ParseAddr'](arg1);
}

export function ResolveAddr(arg1) {
  return window['go']['main']['App']['ResolveAddr'](arg1);
}

export function StartBrowse(arg1) {
  return window['go']['main']['App']['StartBrowse'](arg1);
}

export function StartForward(arg1, arg2) {
  return window['go']['main']['App']['StartForward'](arg1, arg2);
}

export function StartPing(arg1, arg2) {
  return window['go']['main']['App']['StartPing'](arg1, arg2);
}

export function StartPipeServe() {
  return window['go']['main']['App']['StartPipeServe']();
}

export function StartPortServe(arg1) {
  return window['go']['main']['App']['StartPortServe'](arg1);
}

export function StartRecv(arg1, arg2) {
  return window['go']['main']['App']['StartRecv'](arg1, arg2);
}

export function StartCopy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCopy'](arg1, arg2, arg3);
}

export function StartFilesServe(arg1, arg2) {
  return window['go']['main']['App']['StartFilesServe'](arg1, arg2);
}

export function ListRemote(arg1, arg2) {
  return window['go']['main']['App']['ListRemote'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function StartSSHServe(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSSHServe'](arg1, arg2, arg3);
}

export function StartSSHClient(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSSHClient'](arg1, arg2, arg3, arg4);
}

export function StartSOCKS(arg1, arg2) {
  return window['go']['main']['App']['StartSOCKS'](arg1, arg2);
}

export function StartExitNode() {
  return window['go']['main']['App']['StartExitNode']();
}

export function StartExec(arg1) {
  return window['go']['main']['App']['StartExec'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}
